---
# handlers/main.yml
# When getting rid of the crypto keys you have to set the VTY Lines to `transport input all` as a safety measure for management access
- name: Open VTY
  cisco.ios.ios_config:
    lines:
      - "transport input all"
    parents: "{{ item }}"
  loop: "{{ vty }}"

- name: Zeroize Keys
  cisco.ios.ios_command:
    commands:
      - command: "configure terminal"
      - command: "crypto key zeroize rsa"
        prompt: "[yes/no]"
        answer: "yes"

- name: RSA Keys 2048
  cisco.ios.ios_command:
    commands:
      - command: "configure terminal"
      - command: "crypto key generate rsa general-keys modulus 2048"

- name: Harden VTY
  cisco.ios.ios_config:
    lines:
      - "transport input ssh"
    parents: "{{ item }}"
  loop: "{{ vty }}"

- name: Save Configuration
  cisco.ios.ios_config:
    save_when: always
