---
# handlers file for zabbix_proxy
- name: Restart Postgres
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Restart Zabbix Proxy
  ansible.builtin.service:
    name: zabbix-proxy
    state: restarted

- name: Restart Zabbix Agent
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
