# ansible-builder build -v 3
# podman images
# ansible-builder build -t local/netcommon-ee
# podman tag localhost/ansible-execution-env localhost/netcommon-ee
# podman run -it localhost/ansible-execution-env bash
# ansible-galaxy collection list
# podman tag localhost/ansible-execution-env localhost/netcommon-hub-ee
# podman login privatehub-01.$INSTRUQT_PARTICIPANT_ID.instruqt.io --tls-verify=false
# podman tag localhost/ansible-execution-env privatehub-01.$INSTRUQT_PARTICIPANT_ID.instruqt.io/netcommon-hub-ee
# podman push privatehub-01.$INSTRUQT_PARTICIPANT_ID.instruqt.io/netcommon-hub-ee --tls-verify=false
# THEN CHECK YOUR PRIVATE AUTOMATION HUB
---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  galaxy:
    collections:
    - ansible.netcommon

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  # copy arbitary files next to this EE Definition into the build context - we can refer to them later
  - src: files
    dest: configs

additional_build_steps:
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'
