# ansible-builder build -v 3
# podman images
# ansible-builder build -t local/netcommon-ee
# podman tag localhost/ansible-execution-env localhost/netcommon-ee
---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  galaxy:
    collections:
    - ansible.netcommon
    - cisco.ios

options:
  package_manager_path: /usr/bin/microdnf
