# 2025-10-14
---
- name: System Reconnaissance Playbook
  hosts: "{{ target }}"
  gather_facts: true
  become: true

  tasks:
    - name: Refresh package metadata
      shell: yum -q makecache || true
      changed_when: false

    - name: Determine latest available kernel package version
      shell: >
        yum -q list --showduplicates kernel 2>/dev/null | awk '/^kernel(\.|[[:space:]])/{ver=$2} END{print ver}'
      register: available_kernel
      changed_when: false
      failed_when: false

    - name: Check number of available yum updates
      shell: yum check-update | grep .el | wc -l
      register: available_updates_count
      changed_when: false

    - name: Get last patch date from yum history
      shell: yum -q history list | cut -d "|" -f3 | awk 'NR==3{print $1, $2, $3}'
      register: last_patch_date
      changed_when: false
      failed_when: false

    - name: Normalize kernel comparison values using ansible_facts
      set_fact:
        current_kernel: "{{ ansible_facts.kernel | default(ansible_kernel) }}"
        os_version: "{{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}"
        available_kernel_pkgver: "{{ available_kernel.stdout | regex_replace('\\.x86_64$', '') | trim }}"
        running_kernel_pkgver: "{{ (ansible_facts.kernel | default(ansible_kernel)) | regex_replace('\\.x86_64$', '') | trim }}"

    - name: Compute available kernel to display
      set_fact:
        available_kernel_display: >-
          {{
            'No new kernel update available'
            if (available_kernel_pkgver | length == 0)
               or (running_kernel_pkgver in available_kernel_pkgver)
               or (available_kernel_pkgver in running_kernel_pkgver)
            else available_kernel_pkgver
          }}

    - name: Display System Reconnaissance Information
      debug:
        msg:
          - "=========================================="
          - "System Reconnaissance Report"
          - "=========================================="
          - "Hostname: {{ ansible_facts.hostname }}"
          - "Current Kernel Version: {{ current_kernel }}"
          - "Available Kernel Version: {{ available_kernel_display }}"
          - "RHEL OS Version: {{ os_version }}"
          - "Available Yum Updates: {{ available_updates_count.stdout }}"
          - "Last Patch Date: {{ last_patch_date.stdout | trim | default('Unknown', true) }}"
          - "=========================================="
      tags:
        - never
    
    - name: Saving the 'recon_report' to '/tmp' directory
      template:
        src: ../templates/recon_report.j2
        dest: /tmp/recon_report-{{ ansible_date_time.iso8601_basic_short }}.txt
        mode: 755
        owner: root
        group: ems

    - name: Inform the user of the report's location
      debug:
        msg: "Please check the '/tmp' directory for the saved file results"
